def uso(place):
    switcher = {
        "Actividad Fisica": "CJFD",
        "Actividad Fisica Grupall": "CJFD",
        "Aula de Clase Arboleda": "Ambiente de Formacion",
        "Cafeteria Jorge Hoyos": "Servicios de Alimentacion",
        "Casilleros y Centro de Copiado": "Recursos del Campus",
        "Circulacion y Prestamo": "Prestamo de Material Bibliografico",
        "Coleccion Bibliografica p4": "Asesoria y Referencia",
        "Coleccion de Literatura p0": "Ambiente de Estudio Libre",
        "Coleccion Tesis y Hemeroteca": "Busqueda de Material Bibliografico",
        "Coliseo CJFD": "CJFD",
        "Desarrollo de Colecciones y Analisis de Informacion": "Oficinas Administrativas",
        "Direccion Biblioteca": "Oficinas Administrativas",
            "Facultad Comunicacion y Lenguaje": "Ambiente de Estudio Individual",
            "Sala de Alfabetizacion Informacional": "Ambiente de Formacion",
            "Sala de Estudio Grupal Bateman p2": "Ambiente de Estudio Grupal",
            "Sala de Estudio Grupal Rosas p2": "Ambiente de Estudio Grupal",
            "Sala de Estudio Grupal Vasquez p4": "Ambiente de Estudio Grupal",
            "Sala de Estudio Individual - Personas con Limitacion": "Ambiente de Estudio Individual",
            "Sala de Estudio Individual Gaitan p0": "Ambiente de Estudio Individual",
            "Sala de Estudio Individual Lievano p3": "Ambiente de Estudio Individual",
            "Sala de Estudio Individual Miramon p4": "Ambiente de Estudio Individual",
            "Sala de Estudio Individual p1": "Ambiente de Estudio Individual",
            "Sala de Estudio Individual Esguerra p3": "Ambiente de Estudio Individual",
        "Sala de Investigacion p3": "Ambiente de Estudio Individual",
        "Sala de Mercados de Capital": "Ambiente de Formacion",
        "Sala de Periodicos": "Ambiente de Estudio Libre",
        "Sala de Profesores Zuleta": "Ambiente de Estudio Individual",
        "Sala de Tesis y Hemeroteca Olaya": "Ambiente de Estudio Libre",
        "Sala Interactiva s1": "Ambiente Ludico y Estudio Libre",
        "Sala Libros Antiguos y Valiosos": "Asesoria y Referencia Especializada",
        "Salas Privadas de Estudio en Grupo": "Ambiente de Estudio Grupal",
        "Servicios Especializados": "Asesoria y Referencia Especializada",
        "Zona de Estar Arboleda": "Ambiente Libre"
    }
    return (switcher.get(place, "otros"))